home:
    path:  /
    defaults: { _controller: PpaPaloBundle:Default:index }
mostrar:
    path:  /mostrar/{idTipo}
    defaults: { _controller: PpaPaloBundle:Default:mostrar }
contact:
    path:  /contact
    defaults: { _controller: PpaPaloBundle:Default:contacto }
pagproducto:
    path:  /articulo/{idProd}
    defaults: { _controller: PpaPaloBundle:Default:pagproducto }