init:
    path:  /
    defaults: { _controller: PpaPaloBundle:Default:init }
home:
    path:  /{medicina}/
    defaults: { _controller: PpaPaloBundle:Default:index }
    requirements:
        medicina:  Medicina|Poto
mostrar:
    path:  /{medicina}/mostrar/{idTipo}
    defaults: { _controller: PpaPaloBundle:Default:mostrar }
    requirements:
        medicina:  Medicina|Poto
contact:
    path:  /{medicina}/contacto
    defaults: { _controller: PpaPaloBundle:Default:contacto }
    requirements:
        medicina:  Medicina|Poto
pagproducto:
    path:  /{medicina}/articulo/{idProd}
    defaults: { _controller: PpaPaloBundle:Default:pagproducto }
    requirements:
        medicina:  Medicina|Poto