home:
    path:  /
    defaults: { _controller: PpaPaloBundle:Default:index }
mostrar:
    path:  /mostrar/{idTipo}
    defaults: { _controller: PpaPaloBundle:Default:mostrar }
contacto:
    path:  /contacto
    defaults: { _controller: PpaPaloBundle:Default:contacto }
pagproducto:
    path:  /pagproducto
    defaults: { _controller: PpaPaloBundle:Default:pagproducto }