<?php

namespace Ppa\PaloBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoProductoRepository extends EntityRepository {


	public function allTipoProducto ( ) {

		return $this -> getEntityManager( )
    		->createQuery( "

            	SELECT D.docTitulo
				FROM docPEredesBundle:Autor A
				INNER JOIN docPEredesBundle:Documento D WITH A.id = D.id
				WHERE

				A.autApellidoP LIKE '%".$_target."%'

        		")
            ->getResult( );

	}

	public function filteringCategoria ( $_target ) {
		
		return $this -> getEntityManager( )
    		->createQuery( "

            	SELECT D.docTitulo, D.path
				FROM docPEredesBundle:Documento D
				INNER JOIN docPEredesBundle:Categoria C WITH C.id = D.categorias
				WHERE

				C.catNombre LIKE '%".$_target."%'

    		")
            ->getResult( );

	}

}
