ppaPalo:
    resource: "@PpaPaloBundle/Resources/config/routing.yml"
    prefix: /

PpaPaloBundle_producto:
    resource: "@PpaPaloBundle/Resources/config/routing/producto.yml"
    prefix:   /producto

PpaPaloBundle_imagen:
    resource: "@PpaPaloBundle/Resources/config/routing/imagen.yml"
    prefix:   /imagen

PpaPaloBundle_categoria:
    resource: "@PpaPaloBundle/Resources/config/routing/categoria.yml"
    prefix:   /categoria

PpaPaloBundle_tipoproducto:
    resource: "@PpaPaloBundle/Resources/config/routing/tipoproducto.yml"
    prefix:   /tipoproducto

PpaPaloBundle_contacto:
    resource: "@PpaPaloBundle/Resources/config/routing/contacto.yml"
    prefix:   /Contacto

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
user_logout:
       pattern:   /logout